# Use an official PostgreSQL image as a base image.
FROM postgres:latest

# Environment variables to configure PostgreSQL.
ENV POSTGRES_DB mydatabase
ENV POSTGRES_USER myuser
ENV POSTGRES_PASSWORD mypassword
